### ISSUE TITLE
Iniciar sesion

### ISSUE THREAD

**Issue by Nidev-lab** [nicofcabrera/frontFinal-barRC#1]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Quise cerrar sesion al salir.

## Resultado esperado

• Encontrar un boton de "Cerrar sesion" o "Logout".

## Resultado actual

•No se encuentra ningun boton para cerrar sesion.

## Posible solucion

• Que al iniciar sesion los botones de "Ingresar" y "Registrarse" sean remplazados por un boton de cerrar sesion o logout

## Captura

![image](https://github.com/nicofcabrera/frontFinal-barRC/assets/53904695/72785c7b-5bdb-47b0-ae95-ed6ac8dd9492)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by nicofcabrera** [comment]
Hola nico, se realizó los cambios de la navegación.
