### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [nicofcabrera/frontFinal-barRC#2]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Realice unos pedidos.

## Resultado esperado

• Que al hacer mi pedido el modal del carrito se cierre y se eliminen los productos agregados.

## Resultado actual

•El modal no se cierra y los productos agregados se mantienen.

## Captura

![image](https://github.com/nicofcabrera/frontFinal-barRC/assets/53904695/f8c2faaf-099e-4abf-ba03-e3b58811bdc4)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by nicofcabrera** [comment]
Hola nico, se realizó los cambios del carrito.
